name: Cage Audit Action
description: Run cage audit and open/update a GitHub issue with the results.
inputs:
  region:
    description: AWS region to scan.
    required: true
  github-token:
    description: GitHub token used to create/update the issue.
    required: true
  audit-contexts:
    description: Newline-separated JSON file(s) containing audit context (cluster, service).
    required: false
  audit-services:
    description: Newline-separated ECS service(s) to audit in the format `<cluster>/<service>`.
    required: false
  cage-options:
    description: Newline-separated extra options passed to `cage audit`.
    required: false
  issue-title:
    description: Custom issue title. Defaults to "Cage audit report (<region>/<cluster>/<service>)".
    required: false
  dry-run:
    description: If true, do not create/update the issue; only log the summary.
    required: false
    default: "false"
runs:
  using: node24
  main: lib/index.js
